export enum FEATURES {
	DASHBOARD = "DASHBOARD",
	MESSAGES = "MESSAGES",
	USERS = "USERS",
	ADD_USER = "ADD_USER",
	SEND_MESSAGE = "SEND_MESSAGE",
}

export const ROLE_ADMIN = Object.keys(FEATURES);
export const ROLE_MANAGER = [FEATURES.DASHBOARD, FEATURES.MESSAGES, FEATURES.USERS, FEATURES.SEND_MESSAGE];
export const ROLE_MEMBER = [FEATURES.DASHBOARD, FEATURES.MESSAGES, FEATURES.USERS, FEATURES.SEND_MESSAGE];
